export type BitrefillCategory =
  | 'all'
  | 'sa-vouchers'
  | 'airtime'
  | 'streaming'
  | 'gaming'
  | 'gift-cards'
  | 'food'
  | 'travel'
  | 'utilities';

export interface BitrefillDenomination {
  value: number;
  currency: 'ZAR' | 'USD' | 'EUR' | 'GBP';
  label: string;
}

export interface BitrefillProduct {
  id: string;
  name: string;
  fullName: string;
  category: BitrefillCategory;
  description: string;
  denominations: BitrefillDenomination[];
  brandColor: string;
  brandGradient: string;
  textColor: string;
  abbrev: string;
  symbol: string;
  /** Clearbit / CDN logo URL — shown as the primary image; gradient + abbrev used as fallback */
  logoUrl?: string;
  /** Use a white pill/container behind logo for dark-background brands */
  logoBg?: 'white' | 'dark' | 'none';
  popular?: boolean;
  saFeatured?: boolean;
  tag?: string;
  processingTime: string;
  deliveryMethod: string;
  termsNote: string;
}

export const BITREFILL_PRODUCTS: BitrefillProduct[] = [
  // ─── SA Vouchers ─────────────────────────────────────────────────────────────
  {
    id: 'one-voucher',
    name: '1Voucher',
    fullName: '1Voucher South Africa',
    category: 'sa-vouchers',
    description: 'Spend 1Voucher at thousands of online stores across South Africa. No bank account needed.',
    denominations: [
      { value: 10,   currency: 'ZAR', label: 'R10'  },
      { value: 20,   currency: 'ZAR', label: 'R20'  },
      { value: 50,   currency: 'ZAR', label: 'R50'  },
      { value: 100,  currency: 'ZAR', label: 'R100' },
      { value: 150,  currency: 'ZAR', label: 'R150' },
      { value: 200,  currency: 'ZAR', label: 'R200' },
      { value: 500,  currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#E84A17',
    brandGradient: 'linear-gradient(135deg, #E84A17 0%, #FF6B35 100%)',
    textColor: '#FFFFFF',
    abbrev: '1V',
    symbol: '🟠',
    logoUrl: 'https://logo.clearbit.com/1voucher.co.za',
    logoBg: 'white',
    popular: true,
    saFeatured: true,
    tag: 'SA Exclusive',
    processingTime: 'Instant',
    deliveryMethod: 'PIN code via email',
    termsNote: 'Valid for 3 years from purchase. Non-refundable.',
  },
  {
    id: 'blue-voucher',
    name: 'Blue Voucher',
    fullName: 'BlueVoucher South Africa',
    category: 'sa-vouchers',
    description: 'BlueVoucher — the prepaid payment solution accepted across South African online retailers and services.',
    denominations: [
      { value: 5,    currency: 'ZAR', label: 'R5'   },
      { value: 10,   currency: 'ZAR', label: 'R10'  },
      { value: 20,   currency: 'ZAR', label: 'R20'  },
      { value: 50,   currency: 'ZAR', label: 'R50'  },
      { value: 100,  currency: 'ZAR', label: 'R100' },
      { value: 200,  currency: 'ZAR', label: 'R200' },
    ],
    brandColor: '#0066CC',
    brandGradient: 'linear-gradient(135deg, #0052A3 0%, #0099FF 100%)',
    textColor: '#FFFFFF',
    abbrev: 'BV',
    symbol: '🔵',
    logoUrl: 'https://logo.clearbit.com/bluevoucher.co.za',
    logoBg: 'white',
    popular: true,
    saFeatured: true,
    tag: 'SA Exclusive',
    processingTime: 'Instant',
    deliveryMethod: 'PIN code via email',
    termsNote: 'Valid for 12 months. Non-refundable.',
  },
  {
    id: 'kazang',
    name: 'Kazang',
    fullName: 'Kazang Voucher',
    category: 'sa-vouchers',
    description: 'Kazang prepaid vouchers accepted at hundreds of online merchants across Africa.',
    denominations: [
      { value: 10,  currency: 'ZAR', label: 'R10'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#7B2D8B',
    brandGradient: 'linear-gradient(135deg, #6A1B7A 0%, #9C27B0 100%)',
    textColor: '#FFFFFF',
    abbrev: 'KZ',
    symbol: '💜',
    logoUrl: 'https://logo.clearbit.com/kazang.co.za',
    logoBg: 'white',
    saFeatured: true,
    tag: 'SA Exclusive',
    processingTime: 'Instant',
    deliveryMethod: 'PIN code via email',
    termsNote: 'Valid for 24 months.',
  },
  {
    id: 'onecard',
    name: 'OTT Voucher',
    fullName: 'OTT One Card Prepaid',
    category: 'sa-vouchers',
    description: 'OTT OTC vouchers for online payment across South African stores and services.',
    denominations: [
      { value: 25,  currency: 'ZAR', label: 'R25'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 250, currency: 'ZAR', label: 'R250' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#1A6B3A',
    brandGradient: 'linear-gradient(135deg, #145C30 0%, #22A356 100%)',
    textColor: '#FFFFFF',
    abbrev: 'OTT',
    symbol: '💚',
    logoUrl: 'https://logo.clearbit.com/ottvoucher.co.za',
    logoBg: 'white',
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'PIN code via email',
    termsNote: 'Valid for 12 months from purchase.',
  },

  // ─── SA Mobile Airtime ────────────────────────────────────────────────────────
  {
    id: 'mtn-sa',
    name: 'MTN Airtime',
    fullName: 'MTN South Africa Airtime',
    category: 'airtime',
    description: 'Top up any MTN South Africa number instantly. Works for calls, SMS and data bundles.',
    denominations: [
      { value: 10,  currency: 'ZAR', label: 'R10'  },
      { value: 20,  currency: 'ZAR', label: 'R20'  },
      { value: 30,  currency: 'ZAR', label: 'R30'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#FFCC00',
    brandGradient: 'linear-gradient(135deg, #FFCC00 0%, #FF9900 100%)',
    textColor: '#1A1A1A',
    abbrev: 'MTN',
    symbol: '📱',
    logoUrl: 'https://logo.clearbit.com/mtn.com',
    logoBg: 'none',
    popular: true,
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Direct to mobile number',
    termsNote: 'Airtime loaded directly to the specified number. No PIN.',
  },
  {
    id: 'vodacom-sa',
    name: 'Vodacom',
    fullName: 'Vodacom South Africa Airtime',
    category: 'airtime',
    description: 'Instantly top up any Vodacom South Africa prepaid number with airtime.',
    denominations: [
      { value: 10,  currency: 'ZAR', label: 'R10'  },
      { value: 20,  currency: 'ZAR', label: 'R20'  },
      { value: 30,  currency: 'ZAR', label: 'R30'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#E60000',
    brandGradient: 'linear-gradient(135deg, #CC0000 0%, #FF3333 100%)',
    textColor: '#FFFFFF',
    abbrev: 'VDC',
    symbol: '📲',
    logoUrl: 'https://logo.clearbit.com/vodacom.co.za',
    logoBg: 'white',
    popular: true,
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Direct to mobile number',
    termsNote: 'Airtime loaded directly to the specified number. No PIN.',
  },
  {
    id: 'cellc-sa',
    name: 'Cell C',
    fullName: 'Cell C South Africa Airtime',
    category: 'airtime',
    description: 'Top up any Cell C South Africa prepaid number instantly.',
    denominations: [
      { value: 10,  currency: 'ZAR', label: 'R10'  },
      { value: 20,  currency: 'ZAR', label: 'R20'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
    ],
    brandColor: '#E4002B',
    brandGradient: 'linear-gradient(135deg, #BF0022 0%, #FF1744 100%)',
    textColor: '#FFFFFF',
    abbrev: 'CC',
    symbol: '📞',
    logoUrl: 'https://logo.clearbit.com/cellc.co.za',
    logoBg: 'white',
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Direct to mobile number',
    termsNote: 'Airtime loaded directly to the specified number.',
  },
  {
    id: 'telkom-sa',
    name: 'Telkom',
    fullName: 'Telkom South Africa Mobile',
    category: 'airtime',
    description: 'Refill any Telkom Mobile South Africa prepaid number with airtime.',
    denominations: [
      { value: 10,  currency: 'ZAR', label: 'R10'  },
      { value: 20,  currency: 'ZAR', label: 'R20'  },
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
    ],
    brandColor: '#003366',
    brandGradient: 'linear-gradient(135deg, #002244 0%, #0066CC 100%)',
    textColor: '#FFFFFF',
    abbrev: 'TLK',
    symbol: '☎️',
    logoUrl: 'https://logo.clearbit.com/telkom.co.za',
    logoBg: 'white',
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Direct to mobile number',
    termsNote: 'Airtime loaded directly to the specified number.',
  },

  // ─── Streaming ────────────────────────────────────────────────────────────────
  {
    id: 'netflix',
    name: 'Netflix',
    fullName: 'Netflix Gift Card',
    category: 'streaming',
    description: 'Give the gift of Netflix. Redeem for any Netflix plan — Standard, Standard with ads, or Premium.',
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 200,  currency: 'ZAR', label: 'R200'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#E50914',
    brandGradient: 'linear-gradient(135deg, #141414 0%, #E50914 100%)',
    textColor: '#FFFFFF',
    abbrev: 'NETFLIX',
    symbol: '🎬',
    logoUrl: 'https://logo.clearbit.com/netflix.com',
    logoBg: 'dark',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Valid in South Africa only. No expiry.',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    fullName: 'Spotify Gift Card',
    category: 'streaming',
    description: 'Get Spotify Premium and listen to any song, anytime. No ads. Offline listening.',
    denominations: [
      { value: 60,  currency: 'ZAR', label: 'R60 (1 month)'   },
      { value: 120, currency: 'ZAR', label: 'R120 (2 months)' },
      { value: 180, currency: 'ZAR', label: 'R180 (3 months)' },
    ],
    brandColor: '#1DB954',
    brandGradient: 'linear-gradient(135deg, #121212 0%, #1DB954 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Spotify',
    symbol: '🎵',
    logoUrl: 'https://logo.clearbit.com/spotify.com',
    logoBg: 'dark',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'New subscribers only for promotional pricing.',
  },
  {
    id: 'showmax',
    name: 'Showmax',
    fullName: 'Showmax Subscription',
    category: 'streaming',
    description: "Africa's streaming service with the biggest local and international shows, movies and live sport.",
    denominations: [
      { value: 99,  currency: 'ZAR', label: 'R99 — Standard'  },
      { value: 149, currency: 'ZAR', label: 'R149 — Sports'   },
      { value: 299, currency: 'ZAR', label: 'R299 — ProExtra' },
    ],
    brandColor: '#E8212E',
    brandGradient: 'linear-gradient(135deg, #C01020 0%, #F0353D 100%)',
    textColor: '#FFFFFF',
    abbrev: 'SM',
    symbol: '📺',
    logoUrl: 'https://logo.clearbit.com/showmax.com',
    logoBg: 'white',
    saFeatured: true,
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Monthly subscription vouchers. SA residents only.',
  },
  {
    id: 'dstv',
    name: 'DStv',
    fullName: 'DStv MultiChoice Subscription',
    category: 'streaming',
    description: 'Pay your DStv subscription. Access Compact, Compact Plus or Premium packages.',
    denominations: [
      { value: 469,  currency: 'ZAR', label: 'R469 — Compact (1 month)'      },
      { value: 759,  currency: 'ZAR', label: 'R759 — Compact Plus (1 month)' },
      { value: 929,  currency: 'ZAR', label: 'R929 — Premium (1 month)'      },
    ],
    brandColor: '#003882',
    brandGradient: 'linear-gradient(135deg, #002266 0%, #0055BB 100%)',
    textColor: '#FFFFFF',
    abbrev: 'DStv',
    symbol: '📡',
    logoUrl: 'https://logo.clearbit.com/dstv.com',
    logoBg: 'white',
    saFeatured: true,
    popular: true,
    processingTime: 'Up to 24 hours',
    deliveryMethod: 'Direct subscription credit',
    termsNote: 'Requires active DStv account. Enter your smartcard number.',
  },
  {
    id: 'disney-plus',
    name: 'Disney+',
    fullName: 'Disney+ Gift Card',
    category: 'streaming',
    description: 'Unlock Disney+, Star Wars, Marvel, Pixar, National Geographic, and more.',
    denominations: [
      { value: 119, currency: 'ZAR', label: 'R119 (1 month)'  },
      { value: 357, currency: 'ZAR', label: 'R357 (3 months)' },
      { value: 714, currency: 'ZAR', label: 'R714 (6 months)' },
    ],
    brandColor: '#0C3483',
    brandGradient: 'linear-gradient(135deg, #071F5C 0%, #113399 100%)',
    textColor: '#FFFFFF',
    abbrev: 'D+',
    symbol: '✨',
    logoUrl: 'https://logo.clearbit.com/disneyplus.com',
    logoBg: 'dark',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Valid for new and existing subscribers.',
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    fullName: 'Apple TV+ Gift Card',
    category: 'streaming',
    description: 'Stream award-winning Apple Originals — exclusive series, films, and documentaries.',
    denominations: [
      { value: 99,  currency: 'ZAR', label: 'R99 (1 month)'   },
      { value: 297, currency: 'ZAR', label: 'R297 (3 months)' },
    ],
    brandColor: '#555555',
    brandGradient: 'linear-gradient(135deg, #1C1C1E 0%, #3A3A3C 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Apple TV+',
    symbol: '🍎',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    logoBg: 'dark',
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Requires Apple ID. Works on iPhone, iPad, Mac, Apple TV.',
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    fullName: 'YouTube Premium Gift Card',
    category: 'streaming',
    description: 'Ad-free YouTube, YouTube Music, background play and YouTube Originals.',
    denominations: [
      { value: 80,  currency: 'ZAR', label: 'R80 (1 month)'   },
      { value: 160, currency: 'ZAR', label: 'R160 (2 months)' },
      { value: 240, currency: 'ZAR', label: 'R240 (3 months)' },
    ],
    brandColor: '#FF0000',
    brandGradient: 'linear-gradient(135deg, #212121 0%, #FF0000 100%)',
    textColor: '#FFFFFF',
    abbrev: 'YouTube',
    symbol: '▶️',
    logoUrl: 'https://logo.clearbit.com/youtube.com',
    logoBg: 'none',
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'One redemption per Google account.',
  },

  // ─── Gaming ───────────────────────────────────────────────────────────────────
  {
    id: 'playstation',
    name: 'PlayStation',
    fullName: 'PlayStation Store Gift Card',
    category: 'gaming',
    description: 'Top up your PlayStation wallet. Buy PS5 & PS4 games, DLC, PS Plus memberships and more.',
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 250,  currency: 'ZAR', label: 'R250'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#003791',
    brandGradient: 'linear-gradient(135deg, #00194F 0%, #003791 60%, #0070CC 100%)',
    textColor: '#FFFFFF',
    abbrev: 'PS',
    symbol: '🎮',
    logoUrl: 'https://logo.clearbit.com/playstation.com',
    logoBg: 'none',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'ZA PSN account required. Region-locked to South Africa.',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    fullName: 'Xbox Gift Card / Microsoft',
    category: 'gaming',
    description: 'Add funds to your Microsoft account for Xbox games, Game Pass, apps, and more on Xbox and Windows.',
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 250,  currency: 'ZAR', label: 'R250'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#107C10',
    brandGradient: 'linear-gradient(135deg, #0A5A0A 0%, #107C10 60%, #52B043 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Xbox',
    symbol: '🎯',
    logoUrl: 'https://logo.clearbit.com/xbox.com',
    logoBg: 'none',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Requires Microsoft account. Valid in South Africa.',
  },
  {
    id: 'steam',
    name: 'Steam',
    fullName: 'Steam Wallet Gift Card',
    category: 'gaming',
    description: "Add funds to any Steam account — buy games, DLC, and in-game items from the world's largest PC gaming platform.",
    denominations: [
      { value: 5,   currency: 'USD', label: '$5'   },
      { value: 10,  currency: 'USD', label: '$10'  },
      { value: 20,  currency: 'USD', label: '$20'  },
      { value: 50,  currency: 'USD', label: '$50'  },
      { value: 100, currency: 'USD', label: '$100' },
    ],
    brandColor: '#1B2838',
    brandGradient: 'linear-gradient(135deg, #171A21 0%, #1B2838 60%, #2A475E 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Steam',
    symbol: '🖥️',
    logoUrl: 'https://logo.clearbit.com/steampowered.com',
    logoBg: 'none',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Must be redeemed in USD region Steam account.',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    fullName: 'Nintendo eShop Gift Card',
    category: 'gaming',
    description: 'Purchase games, downloadable content, and more from Nintendo eShop on Nintendo Switch.',
    denominations: [
      { value: 15, currency: 'USD', label: '$15' },
      { value: 25, currency: 'USD', label: '$25' },
      { value: 50, currency: 'USD', label: '$50' },
    ],
    brandColor: '#E60012',
    brandGradient: 'linear-gradient(135deg, #C0000E 0%, #E60012 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Nintendo',
    symbol: '🕹️',
    logoUrl: 'https://logo.clearbit.com/nintendo.com',
    logoBg: 'white',
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Works with US Nintendo Account. Region may apply.',
  },
  {
    id: 'roblox',
    name: 'Roblox',
    fullName: 'Roblox Gift Card',
    category: 'gaming',
    description: 'Get Robux — the in-game currency for Roblox. Buy premium items, game passes and avatar accessories.',
    denominations: [
      { value: 10, currency: 'USD', label: '$10 — 800 Robux'   },
      { value: 25, currency: 'USD', label: '$25 — 2,000 Robux' },
      { value: 50, currency: 'USD', label: '$50 — 4,500 Robux' },
    ],
    brandColor: '#E02020',
    brandGradient: 'linear-gradient(135deg, #B01010 0%, #E02020 60%, #FF4040 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Roblox',
    symbol: '🟥',
    logoUrl: 'https://logo.clearbit.com/roblox.com',
    logoBg: 'white',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'For Roblox accounts. Robux added to account balance.',
  },
  {
    id: 'valorant',
    name: 'Valorant',
    fullName: 'Riot Games / Valorant VP',
    category: 'gaming',
    description: "Purchase Valorant Points (VP) to unlock agents, skins, battle passes and more in Riot's tactical FPS.",
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100 — 420 VP'     },
      { value: 200,  currency: 'ZAR', label: 'R200 — 900 VP'     },
      { value: 500,  currency: 'ZAR', label: 'R500 — 2,450 VP'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000 — 5,350 VP' },
    ],
    brandColor: '#FF4655',
    brandGradient: 'linear-gradient(135deg, #0F1923 0%, #FF4655 100%)',
    textColor: '#FFFFFF',
    abbrev: 'VALO',
    symbol: '⚡',
    logoUrl: 'https://logo.clearbit.com/playvalorant.com',
    logoBg: 'none',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'SA Riot account required. Region-locked.',
  },

  // ─── Gift Cards ───────────────────────────────────────────────────────────────
  {
    id: 'amazon',
    name: 'Amazon',
    fullName: 'Amazon Gift Card',
    category: 'gift-cards',
    description: 'Shop millions of products on Amazon.com — electronics, books, fashion and more.',
    denominations: [
      { value: 10,  currency: 'USD', label: '$10'  },
      { value: 25,  currency: 'USD', label: '$25'  },
      { value: 50,  currency: 'USD', label: '$50'  },
      { value: 100, currency: 'USD', label: '$100' },
      { value: 200, currency: 'USD', label: '$200' },
    ],
    brandColor: '#FF9900',
    brandGradient: 'linear-gradient(135deg, #232F3E 0%, #FF9900 100%)',
    textColor: '#FFFFFF',
    abbrev: 'amazon',
    symbol: '📦',
    logoUrl: 'https://logo.clearbit.com/amazon.com',
    logoBg: 'none',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Claim code via email',
    termsNote: 'Valid on Amazon.com (US). No expiry on promotional balance.',
  },
  {
    id: 'google-play',
    name: 'Google Play',
    fullName: 'Google Play Gift Card',
    category: 'gift-cards',
    description: 'Buy apps, games, movies, books and more from the Google Play Store on Android devices.',
    denominations: [
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#01875F',
    brandGradient: 'linear-gradient(135deg, #34A853 0%, #4285F4 50%, #EA4335 100%)',
    textColor: '#FFFFFF',
    abbrev: '▶ Play',
    symbol: '🤖',
    logoUrl: 'https://logo.clearbit.com/play.google.com',
    logoBg: 'white',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'ZA Google account required. Non-transferable.',
  },
  {
    id: 'apple-itunes',
    name: 'Apple / iTunes',
    fullName: 'Apple Gift Card (App Store & iTunes)',
    category: 'gift-cards',
    description: 'Use on the App Store, iTunes Store, Apple TV, Apple Arcade, Apple Music and iCloud storage.',
    denominations: [
      { value: 50,   currency: 'ZAR', label: 'R50'    },
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 200,  currency: 'ZAR', label: 'R200'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#555555',
    brandGradient: 'linear-gradient(135deg, #1C1C1E 0%, #3A3A3C 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Apple',
    symbol: '🍎',
    logoUrl: 'https://logo.clearbit.com/apple.com',
    logoBg: 'dark',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'ZA Apple ID required. Non-refundable.',
  },
  {
    id: 'takealot',
    name: 'Takealot',
    fullName: 'Takealot Gift Voucher',
    category: 'gift-cards',
    description: "Shop South Africa's biggest online store — electronics, fashion, home, sports and more.",
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 250,  currency: 'ZAR', label: 'R250'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#0099CC',
    brandGradient: 'linear-gradient(135deg, #007AA3 0%, #00AADD 100%)',
    textColor: '#FFFFFF',
    abbrev: 'takealot',
    symbol: '🛍️',
    logoUrl: 'https://logo.clearbit.com/takealot.com',
    logoBg: 'white',
    popular: true,
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Voucher code via email',
    termsNote: 'Valid for 2 years from purchase. SA only.',
  },
  {
    id: 'woolworths',
    name: 'Woolworths',
    fullName: 'Woolworths Gift Card',
    category: 'gift-cards',
    description: 'Shop Woolworths stores for quality food, fashion, beauty and home products across South Africa.',
    denominations: [
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 250,  currency: 'ZAR', label: 'R250'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#374151',
    brandGradient: 'linear-gradient(135deg, #1F2937 0%, #4B5563 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Woolworths',
    symbol: '🛒',
    logoUrl: 'https://logo.clearbit.com/woolworths.co.za',
    logoBg: 'white',
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Voucher code via email',
    termsNote: 'Valid in all Woolworths stores. No expiry.',
  },
  {
    id: 'uber',
    name: 'Uber',
    fullName: 'Uber Gift Card',
    category: 'gift-cards',
    description: 'Get rides or food delivery with Uber. Works across South Africa and globally.',
    denominations: [
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#000000',
    brandGradient: 'linear-gradient(135deg, #000000 0%, #1A1A1A 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Uber',
    symbol: '🚗',
    logoUrl: 'https://logo.clearbit.com/uber.com',
    logoBg: 'dark',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Promo code via email',
    termsNote: 'One use per Uber account. Expires 12 months from purchase.',
  },
  {
    id: 'uber-eats',
    name: 'Uber Eats',
    fullName: 'Uber Eats Gift Card',
    category: 'gift-cards',
    description: 'Order food delivery from your favourite restaurants in South Africa with Uber Eats.',
    denominations: [
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#06C167',
    brandGradient: 'linear-gradient(135deg, #04A050 0%, #06C167 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Uber Eats',
    symbol: '🍔',
    logoUrl: 'https://logo.clearbit.com/ubereats.com',
    logoBg: 'white',
    processingTime: 'Instant',
    deliveryMethod: 'Promo code via email',
    termsNote: 'One use per Uber account. Expires 12 months from purchase.',
  },

  // ─── Food ─────────────────────────────────────────────────────────────────────
  {
    id: 'kfc',
    name: 'KFC',
    fullName: 'KFC South Africa Gift Voucher',
    category: 'food',
    description: 'Redeem at KFC restaurants across South Africa. Dine in, take away, or delivery.',
    denominations: [
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
    ],
    brandColor: '#E4002B',
    brandGradient: 'linear-gradient(135deg, #BA0020 0%, #E4002B 60%, #F40030 100%)',
    textColor: '#FFFFFF',
    abbrev: 'KFC',
    symbol: '🍗',
    logoUrl: 'https://logo.clearbit.com/kfc.com',
    logoBg: 'none',
    popular: true,
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Voucher code via email',
    termsNote: 'Valid at participating KFC SA locations.',
  },
  {
    id: 'mcdonalds',
    name: "McDonald's",
    fullName: "McDonald's South Africa Gift Card",
    category: 'food',
    description: "Enjoy your favourite McDonald's meals across South Africa. Big Mac, Chicken McNuggets and more.",
    denominations: [
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
    ],
    brandColor: '#DA291C',
    brandGradient: 'linear-gradient(135deg, #C1272D 0%, #DA291C 50%, #FFC72C 100%)',
    textColor: '#FFFFFF',
    abbrev: "McDonald's",
    symbol: '🍟',
    logoUrl: 'https://logo.clearbit.com/mcdonalds.com',
    logoBg: 'none',
    popular: true,
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Voucher code via email',
    termsNote: "Valid at participating McDonald's SA locations.",
  },
  {
    id: 'nandos',
    name: "Nando's",
    fullName: "Nando's PERi-PERi Gift Card",
    category: 'food',
    description: "Redeem at Nando's restaurants across South Africa. Famous for flame-grilled PERi-PERi chicken.",
    denominations: [
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#CB3228',
    brandGradient: 'linear-gradient(135deg, #9B1C14 0%, #CB3228 60%, #E64040 100%)',
    textColor: '#FFFFFF',
    abbrev: "Nando's",
    symbol: '🔥',
    logoUrl: 'https://logo.clearbit.com/nandos.co.za',
    logoBg: 'white',
    saFeatured: true,
    processingTime: 'Instant',
    deliveryMethod: 'Gift card code via email',
    termsNote: "Valid at all Nando's SA restaurants.",
  },
  {
    id: 'starbucks',
    name: 'Starbucks',
    fullName: 'Starbucks Gift Card',
    category: 'food',
    description: 'Treat yourself or someone else to Starbucks coffee, tea, or food items.',
    denominations: [
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#00704A',
    brandGradient: 'linear-gradient(135deg, #004D33 0%, #00704A 100%)',
    textColor: '#FFFFFF',
    abbrev: 'Starbucks',
    symbol: '☕',
    logoUrl: 'https://logo.clearbit.com/starbucks.com',
    logoBg: 'none',
    processingTime: 'Instant',
    deliveryMethod: 'eGift card code via email',
    termsNote: 'Valid at participating Starbucks stores.',
  },

  // ─── Travel ───────────────────────────────────────────────────────────────────
  {
    id: 'airbnb',
    name: 'Airbnb',
    fullName: 'Airbnb Gift Card',
    category: 'travel',
    description: 'Book unique stays and experiences around the world with Airbnb.',
    denominations: [
      { value: 25,  currency: 'USD', label: '$25'  },
      { value: 50,  currency: 'USD', label: '$50'  },
      { value: 100, currency: 'USD', label: '$100' },
      { value: 200, currency: 'USD', label: '$200' },
    ],
    brandColor: '#FF5A5F',
    brandGradient: 'linear-gradient(135deg, #E0474C 0%, #FF5A5F 100%)',
    textColor: '#FFFFFF',
    abbrev: 'airbnb',
    symbol: '🏠',
    logoUrl: 'https://logo.clearbit.com/airbnb.com',
    logoBg: 'white',
    popular: true,
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Must be applied to a valid Airbnb account. Non-refundable.',
  },
  {
    id: 'booking',
    name: 'Booking.com',
    fullName: 'Booking.com Gift Card',
    category: 'travel',
    description: 'Book hotels, apartments, and more in 220+ countries worldwide.',
    denominations: [
      { value: 25,  currency: 'USD', label: '$25'  },
      { value: 50,  currency: 'USD', label: '$50'  },
      { value: 100, currency: 'USD', label: '$100' },
    ],
    brandColor: '#003580',
    brandGradient: 'linear-gradient(135deg, #002060 0%, #003580 60%, #0071C2 100%)',
    textColor: '#FFFFFF',
    abbrev: 'booking',
    symbol: '🏨',
    logoUrl: 'https://logo.clearbit.com/booking.com',
    logoBg: 'none',
    processingTime: 'Instant',
    deliveryMethod: 'Redemption code via email',
    termsNote: 'Valid for all bookings. No expiry.',
  },

  // ─── Utilities ────────────────────────────────────────────────────────────────
  {
    id: 'eskom-prepaid',
    name: 'Prepaid Electricity',
    fullName: 'SA Prepaid Electricity (Eskom / Municipalities)',
    category: 'utilities',
    description: 'Buy prepaid electricity tokens for Eskom or any South African municipality. Enter your meter number.',
    denominations: [
      { value: 50,   currency: 'ZAR', label: 'R50'    },
      { value: 100,  currency: 'ZAR', label: 'R100'   },
      { value: 200,  currency: 'ZAR', label: 'R200'   },
      { value: 500,  currency: 'ZAR', label: 'R500'   },
      { value: 1000, currency: 'ZAR', label: 'R1,000' },
    ],
    brandColor: '#F59E0B',
    brandGradient: 'linear-gradient(135deg, #D97706 0%, #F59E0B 60%, #FCD34D 100%)',
    textColor: '#1A1A1A',
    abbrev: '⚡',
    symbol: '⚡',
    logoUrl: 'https://logo.clearbit.com/eskom.co.za',
    logoBg: 'white',
    popular: true,
    saFeatured: true,
    tag: 'Utility',
    processingTime: 'Up to 30 min',
    deliveryMethod: 'Token via email + SMS',
    termsNote: 'Requires valid SA prepaid meter number. Non-refundable.',
  },
  {
    id: 'sa-water',
    name: 'Prepaid Water',
    fullName: 'SA Prepaid Water Meter',
    category: 'utilities',
    description: 'Purchase prepaid water tokens for South African municipal meters.',
    denominations: [
      { value: 50,  currency: 'ZAR', label: 'R50'  },
      { value: 100, currency: 'ZAR', label: 'R100' },
      { value: 200, currency: 'ZAR', label: 'R200' },
      { value: 500, currency: 'ZAR', label: 'R500' },
    ],
    brandColor: '#0EA5E9',
    brandGradient: 'linear-gradient(135deg, #0284C7 0%, #0EA5E9 60%, #38BDF8 100%)',
    textColor: '#FFFFFF',
    abbrev: '💧',
    symbol: '💧',
    logoUrl: 'https://logo.clearbit.com/capetown.gov.za',
    logoBg: 'white',
    saFeatured: true,
    tag: 'Utility',
    processingTime: 'Up to 30 min',
    deliveryMethod: 'Token via email + SMS',
    termsNote: 'Requires valid SA prepaid water meter number.',
  },
];

export const CATEGORY_CONFIG: Record<BitrefillCategory, { label: string; icon: string; description: string }> = {
  'all':         { label: 'All Products',  icon: '🌐', description: 'Browse everything Bitrefill offers'     },
  'sa-vouchers': { label: 'SA Vouchers',   icon: '🇿🇦', description: '1Voucher, BlueVoucher & more'          },
  'airtime':     { label: 'Airtime',       icon: '📱', description: 'MTN, Vodacom, Cell C & Telkom top-ups'  },
  'streaming':   { label: 'Streaming',     icon: '🎬', description: 'Netflix, DStv, Showmax & more'          },
  'gaming':      { label: 'Gaming',        icon: '🎮', description: 'PlayStation, Xbox, Steam & more'        },
  'gift-cards':  { label: 'Gift Cards',    icon: '🎁', description: 'Amazon, Takealot, Google Play & more'   },
  'food':        { label: 'Food',          icon: '🍔', description: "KFC, McDonald's, Nando's & more"        },
  'travel':      { label: 'Travel',        icon: '✈️', description: 'Airbnb, Booking.com & more'             },
  'utilities':   { label: 'Utilities',     icon: '⚡', description: 'Electricity & water prepaid tokens'     },
};
